### ISSUE TITLE
docker_ubuntu unexpectedly alters Ansible environment

### ISSUE THREAD

**Issue by gotgenes** [angstwad/docker.ubuntu#101]
I must execute docker_ubuntu role with `become: yes` because it requires administrative privileges to do the tasks. The [final task in docker_ubuntu](https://github.com/angstwad/docker.ubuntu/blob/c0a4f06b0db174c54ffaee222019f6be1386b2c3/tasks/main.yml#L187) performs a [`setup`](http://docs.ansible.com/ansible/setup_module.html) action, which alters variables. In my case, tasks in roles following the docker_ubuntu role needed to use the `HOME` environment variable, but the call to `setup` caused my environment to be set to `root`'s environment (and therefore, `HOME` to be set to `/root`).

Is there a way to avoid calling `setup`, or at the very least, can it please be much more tightly restricted (see [the available options for `setup`](http://docs.ansible.com/ansible/setup_module.html#options))? I don't understand to what this `docker.io` relates. It appears to be a deprecated name for the Docker package. If it is, could this please be removed entirely?

**Comment by angstwad** [comment]
Setup was introduced in  https://github.com/angstwad/docker.ubuntu/pull/63 to make sure that it picks up the latest facts from the system post install.  

I'd take a PR that allows one to disable the setup call, with the default being keeping existing functionality.

Alternatively you could run setup after this role runs as the user you want setup run.
