### ISSUE TITLE
Cannot install kernel extras but not upgrade the current running kernel

### ISSUE THREAD

**Issue by juanbrein** [angstwad/docker.ubuntu#103]
When setting:

kernel_pkg_state: present
install_kernel_extras: true

The expected behaviour should be to install the current kernel extras. However a kernel upgrade is performed. I believe the problem is because you are installing linux-image-extra-virtual and that is not versioned so it'll trigger a kernel upgrade regardless.

This is on Ubuntu 14.04

Thanks

**Comment by angstwad** [comment]
I'll look into this when I get some time, and but if a good PR comes in for that I'll be able to merge faster than I duplicate the problem and fix.

**Comment by lhoss** [comment]
> I believe the problem is because you are installing linux-image-extra-virtual and that is not versioned so it'll trigger a kernel upgrade regardless.

I can confirm, that's exactly the problem (I noticed it on our Ub. 14.04 servers, where we use v4.2.x kernel)!
After `linux-image-extra-virtual` removed, no unneeded kernel upgrade!
I'ld suggest to simply remove that (if nobody can tell why it's required)
-> 1 line PR 👍

**Comment by lhoss** [comment]
any updates here?

**Comment by angstwad** [comment]
If this is still an issue, please reopen.
