### ISSUE TITLE
version checking can give unexpected results

### ISSUE THREAD

**Issue by berlic** [angstwad/docker.ubuntu#104]
`version_compare(12.04, '<')` can lead to unexpected comparison result, `version_compare('12.04', '<')` should be used instead.

**Comment by angstwad** [comment]
I'll look into this when I get some time, and but if a good PR comes in for that I'll be able to merge faster than I duplicate the problem and fix.

**Comment by boristimp** [comment]
Created #134

**Comment by angstwad** [comment]
This is done.
