### ISSUE TITLE
Getting multiple errors with ansible 2.1.1.0

### ISSUE THREAD

**Issue by ArtworkAD** [angstwad/docker.ubuntu#108]
ERROR! Syntax Error while loading YAML.

> The error appears to have been in '/ansible/roles/angstwad.docker_ubuntu/LICENSE': line 92, column 36, but may
> be elsewhere in the file depending on the exact syntax problem.
> 
> The offending line appears to be:
> 
>       modifications, and in Source or Object form, provided that You
>       meet the following conditions:
>                                    ^ here
> 
> /ansible/roles/angstwad.docker_ubuntu/LICENSE:1: Expected key=value host variable assignment, got: License

when I remove this file:

> ERROR! /ansible/roles/angstwad.docker_ubuntu/README.md:4: Invalid section entry: '[![Build Status](https://travis-ci.org/angstwad/docker.ubuntu.svg)](https://travis-ci.org/angstwad/docker.ubuntu)'. Please make sure that there are no spacesin the section entry, and that there are no other invalid characters

when I remove it:

> ERROR! Syntax Error while loading YAML.
> 
> 
> The error appears to have been in '/ansible/roles/angstwad.docker_ubuntu/Vagrantfile': line 37, column 42, but may
> be elsewhere in the file depending on the exact syntax problem.
> 
> The offending line appears to be:
> 
> 
>       vms.vm.network :private_network, ip: box[:ip]
>                                          ^ here
> 
> /ansible/roles/angstwad.docker_ubuntu/Vagrantfile:4: Expected key=value host variable assignment, got: File.basename(File.expand_path(File.dirname(__FILE__)))

and when I finally remove this I get:

> ERROR! 'AnsibleSequence' object has no attribute 'keys'
> /ansible/roles/angstwad.docker_ubuntu/docker.yml:2: Expected key=value host variable assignment, got: hosts:

any idea whats wrong?

**Comment by angstwad** [comment]
I have no idea why this is happening, but Ansible is trying to load non-yaml files.  Make sure you're running the latest version of ansible, and check your `roles_path` ([docs here](http://docs.ansible.com/ansible/intro_configuration.html#roles-path)).

Are you using this as a role?  Don't use `include` here.

**Comment by angstwad** [comment]
This isn't an issue with this role; closing.
