### ISSUE TITLE
Proposed method of specifying docker_opts - doesn't work

### ISSUE THREAD

**Issue by fitz123** [angstwad/docker.ubuntu#111]
Recommended way to specify options doesn't work. Example is bellow

My opts variable looks like this
```
# The following help expose a docker port or to add additional options when
# running docker daemon.  The default is to not use any special options.
#docker_opts: >
#  -H unix://
#  -H tcp://0.0.0.0:2375
#  --log-level=debug
docker_opts: >
  -H unix:///var/run/docker.sock
  -H tcp://0.0.0.0:2376
  --tlsverify 
  --tlscacert=/etc/ssl/certs/docker-ca.pem 
  --tlscert=/etc/ssl/certs/{{ hostname }}-cert.pem
  --tlskey=/etc/ssl/private/{{ hostname }}-priv-key.pem
# List of users to be added to 'docker' system group (disabled by default)
...
```

It produces followed result:
```
$ cat /etc/systemd/system/docker.service.d/env.conf 
[Service]
Environment="DOCKER_OPTS=-H unix:///var/run/docker.sock -H tcp://0.0.0.0:2376 --tlsverify --tlscacert=/etc/ssl/certs/docker-ca.pem --tlscert=/etc/ssl/certs/docker-host-n1-cert.pem --tlskey=/etc/ssl/private/docker-host-n1-priv-key.pem
"
```

Because double quotes located on the new line, no parameters are actually applied. 

I fixed it by specifying opts in old-style-one-line way:

```
docker_opts: "-H unix:///var/run/docker.sock -H tcp://0.0.0.0:2376 --tlsverify --tlscacert=/etc/ssl/certs/docker-ca.pem --tlscert=/etc/ssl/certs/{{ hostname }}-cert.pem --tlskey=/etc/ssl/private/{{ hostname }}-priv-key.pem"
```

And now it works fine

**Comment by angstwad** [comment]
I'll take a PR that fixes the service file for this

**Comment by fitz123** [comment]
Do you have any ideas how to fix it, or using one-line parameters is good enough solution?
I'd try to do a list for opts parameters to make it looks good, and compile a service file out of template rather than use lineinfile magic

**Comment by angstwad** [comment]
No PR needed.  I misunderstood the issue. Looks like it's the way you're declaring that block.  You can try using `>-`.  

See https://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines for more.
