### ISSUE TITLE
option to downgrade version of docker

### ISSUE THREAD

**Issue by oppianmatt** [angstwad/docker.ubuntu#114]
Can't see it in the readme. Can see `update_docker_package` which will set it to latest.

Want to downgrade my docker from 1.12.2 to 1.12.1 since this regression bug https://github.com/docker/docker/issues/27540

Note we can set `docker_pkg_name` to something like: `docker_pkg_name: docker-engine=1.12.1-*` and it tries to downgrade, but since it's not using force option for apt it fails.

**Comment by mlaventure** [comment]
`apt-get install docker-engine=1.12.1-0~trusty` works for me (I'm on ubuntu trusty).

To see the available version you can use `apt-get policy docker-engine`

**Comment by DEVELByte** [comment]
for fedora :
`sudo yun downgrade docker-engine-1.12.1`

Ubuntu as suggested by @mlaventure: 
`sudo apt-get install docker-engine=1.12.1-0~trusty`

**Comment by oppianmatt** [comment]
I prefer 'sudo apt-get install 'docker-engine=1.12.1*'

But of course I can do it ion the command line, that's not the issue. The issue is that I wanted to use ansible to do it (and have my playbook in my respository to repeat it). 

Point is that I shouldn't have to ssh into a server to fix, that I could fix the ansible scripts and it will apply my changes.

The ansible role just needs a `force=yes` so we can install specific versions.

**Comment by lhoss** [comment]
@oppianmatt (as an active role contributor) I suggest to propose a downward-compatible PR, by adding a new variable  (`docker_install_force: false`) to be used with the added `force` attribute.
So it's disabled by default, but you can enable on demand.

**Comment by monikakatiyar16** [comment]
None of the above options worked well for me to downgrade the version from 17.05.0-ce to 1.13.1. However, this worked well for me:

> curl -fsSLO https://get.docker.com/builds/Linux/x86_64/docker-1.13.1.tgz && tar --strip-components=1 -xvzf docker-1.13.1.tgz -C /usr/local/bin
