### ISSUE TITLE
Doesn't work on Ubuntu 14.04 since November 15th

### ISSUE THREAD

**Issue by bitbauer** [angstwad/docker.ubuntu#117]
In a running project role role runs in to an TLS handshake error, when apt tries to update https://apt.dockerproject.org/repo/dists/ubuntu-trusty/
(see below)
This is more related to dockerproject apt repository, Ubuntu 14.04 and Vagrantbox "ubuntu/trusty64" that I use...
but at the end it stops working with Ubuntu 14.04. I'm going ahead in project with Ubuntu 16.04, because it makes sense anyway. 

```
==> localhost: TASK [angstwad.docker_ubuntu : Add Docker repository and update apt cache] *****
==> localhost: An exception occurred during task execution. To see the full traceback, use -vvv. The error was: , E:Some index files failed to download. They have been ignored, or old ones used instead.
==> localhost: fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_Xe78FR/ansible_module_apt_repository.py\", line 525, in <module>\n    main()\n  File \"/tmp/ansible_Xe78FR/ansible_module_apt_repository.py\", line 515, in main\n    cache.update()\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 440, in update\n    raise FetchFailedException(e)\napt.cache.FetchFailedException: W:Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-trusty/main/binary-amd64/Packages  gnutls_handshake() failed: Handshake failed\n, E:Some index files failed to download. They have been ignored, or old ones used instead.\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```

and thank you for contributing it for all 👍

**Comment by angstwad** [comment]
I'll quickly merge a PR that works around or resolves this issue.

**Comment by rjduffner** [comment]
@angstwad, any updates on this issue?

**Comment by angstwad** [comment]
I haven't looked into this issue at all, but i'm happy to take a PR for it.

**Comment by rjduffner** [comment]
Ok I can try to take a look.

**Comment by rjduffner** [comment]
Hmm now that I am looking at it, this seems to be a slightly different issue than the one I had a fix for. I may look at this one after but I will open a new issue for my issue.

**Comment by rjduffner** [comment]
@bitbauer, I can't seem to repo it using the test steps outlined in the README. Does it repo there for you?

**Comment by angstwad** [comment]
Can't repro.
