### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by angstwad** [angstwad/docker.ubuntu#120]
They're broken.

**Comment by mtbvang** [comment]
By tests do you mean the ones run with test/vagrant.yml?I'm working on #132 and am running them locally and have gotten them to work. How were they broken when you logged this issue?

**Comment by mtbvang** [comment]
@angstwad I'm new to ansible and was wondering what the best framework to put some test assertions in is? The travis and docker approach just seems to check that the palybook runs but not functioning as expected.

**Comment by mtbvang** [comment]
@angstwad Is there a reason why the vagrant tests are run on VMs and the Travis are run on docker contaners?

**Comment by angstwad** [comment]
Just the nature of the tests.  Ideally, the Travis tests run a full install of docker inside all the supported versions of Ubuntu and Debian, and we just validate all the appropriate steps for each version run and do what they're supposed to do.   Travis supports docker, so we can install docker inside Travis' docker to make sure each runs.

As far as the Vagrant tests go, we just need to add 16.04 to the Vagrantfile.

**Comment by mtbvang** [comment]
I got the vagrant tests running and the Travis docker tests are almost
there. I just need to get rid of some errors.  Hopefully I can submit a PR
Monday.

**Comment by mtbvang** [comment]
The vagrant tests are failing with the following. Is this related to #135?

```
TASK [docker.ubuntu : Install pip, setuptools, docker-py and docker-compose with pip] ***
Friday 20 January 2017  16:54:09 +0100 (0:00:59.506)       0:04:05.535 ******** 
failed: [ubuntu1204] (item={u'version': u'latest', u'name': u'pip', u'install': True}) => {"cmd": "/usr/bin/pip install -U pip", "failed": true, "item": {"install": true, "name": "pip", "version": "latest"}, "msg": "stdout: Downloading/unpacking pip\n  Cannot fetch index base URL http://pypi.python.org/simple/\n  Could not find any downloads that satisfy the requirement pip\nNo distributions at all found for pip\nStoring complete log in /root/.pip/pip.log\n"}
failed: [ubuntu1204] (item={u'version': u'latest', u'name': u'setuptools', u'install': True}) => {"cmd": "/usr/bin/pip install -U setuptools", "failed": true, "item": {"install": true, "name": "setuptools", "version": "latest"}, "msg": "stdout: Downloading/unpacking distribute\n  Cannot fetch index base URL http://pypi.python.org/simple/\n  Could not find any downloads that satisfy the requirement distribute\nNo distributions at all found for distribute\nStoring complete log in /root/.pip/pip.log\n"}
failed: [ubuntu1204] (item={u'version': u'latest', u'name': u'docker-py', u'install': True}) => {"cmd": "/usr/bin/pip install -U docker-py", "failed": true, "item": {"install": true, "name": "docker-py", "version": "latest"}, "msg": "stdout: Downloading/unpacking docker-py\n  Cannot fetch index base URL http://pypi.python.org/simple/\n  Could not find any downloads that satisfy the requirement docker-py\nNo distributions at all found for docker-py\nStoring complete log in /root/.pip/pip.log\n"}
failed: [ubuntu1204] (item={u'version': u'latest', u'name': u'docker-compose', u'install': True}) => {"cmd": "/usr/bin/pip install -U docker-compose", "failed": true, "item": {"install": true, "name": "docker-compose", "version": "latest"}, "msg": "stdout: Downloading/unpacking docker-compose\n  Cannot fetch index base URL http://pypi.python.org/simple/\n  Could not find any downloads that satisfy the requirement docker-compose\nNo distributions at all found for docker-compose\nStoring complete log in /root/.pip/pip.log\n"}
```

**Comment by mtbvang** [comment]
I'm running the docker hello-world container on the Travis build to test the install and  for some reason the ubuntu 14.04 container is failing. The vagrant VM works fine. So I've got one broken VM and one broken container based test. Arghh...

`fatal: [ubuntu1404]: FAILED! => {"changed": true, "cmd": "docker run hello-world", "delta": "0:00:00.086750", "end": "2017-01-20 16:35:38.298365", "failed": true, "rc": 125, "start": "2017-01-20 16:35:38.211615", "stderr": "docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.\nSee 'docker run --help'.", "stdout": "", "stdout_lines": [], "warnings": []}`

**Comment by mtbvang** [comment]
Looks like the pip errors above for ubuntu 1204 are a result of a pip 1.0 bug with proxies http://askubuntu.com/questions/767157/cannot-upgrade-pip-behind-proxy. Will install pip with easy_install when proxy detected.

**Comment by mtbvang** [comment]
@angstwad I have to park this for the time being, but will keep working on it when I can because I really want to get these tests running. Is it worth still supporting ubuntu 12.04?

Is the testing using docker containers on Travis a good approach? I think it is to extend the test coverage for docker in docker, but is that something that should be supported? This is where I'm at:

Running the hello-world docker test on ubuntu 12.04 is not working on the vagrant vm due to the error: 
`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? `
I haven't figured out what's causing this and have tried adding the vagrant user to the docker group and restarting with no success. I haven't tried setting the docker_group_members variable and getting the 'Add users to the docker group' task to do it.

The Travis CI tests are run on docker containers are failing due to systemctl and systemd not working for debian jessie and ubuntu 16.04 containers. The tests are at the point where a container of the right OS flavour is being spun up and the role applied and the hello-world test is failing. I also tested a branch that has Ansible < and > 2. The > 2 tests run, but the < 2 fails due to ansible < 2 not supporting blocks statements used by the provision_docker role. I based the work on https://www.ansible.com/blog/testing-ansible-roles-with-docker.

**Comment by mtbvang** [comment]
Got the Travis tests running. Looks like they were failing because of some docker ops that were set on the role.

**Comment by sean-abbott** [comment]
I'm using molecule and using this role as a dependency for my role, and unfortunately this role is failing molecule's idempotency test.  
```
ERROR: Idempotence test failed because of the following tasks:
ERROR: * [datacenter-docker] => angstwad.docker_ubuntu : Install pip, setuptools, docker-py and docker-compose with pip
* [datacenter-docker] => angstwad.docker_ubuntu : Install pip, setuptools, docker-py and docker-compose with pip
```
Currently just trying to figure out how to disable those tests for molecule...

**Comment by hurricanehrndz** [comment]
@angstwad 
Would you be open to a pull request that uses test-kitchen and serverspec for tests? The test will cover both armhf and amd64.

**Comment by hurricanehrndz** [comment]
@angstwad,

so I have test-kitchen working  on amd64, unfortunately in terms of running docker within docker on arm currently  there is an issue with running docker under qemu.
