### ISSUE TITLE
Docker package incorrect for 16.04

### ISSUE THREAD

**Issue by pmyjavec** [angstwad/docker.ubuntu#121]
By default, the package `docker-engine` is unable to be found on 16.04 hosts. This should be set to `docker.io` for said hosts.

I'll try do this one myself :)

**Comment by pmyjavec** [comment]
THis wa

**Comment by pmyjavec** [comment]
This was my bad, was accidently running 32bit Ubuntu. Maybe it's worth blowing up if the arch is wrong ?

**Comment by angstwad** [comment]
I'd take a PR for an architecture check.
