### ISSUE TITLE
docker_opts ineffective when docker is managed via systemd

### ISSUE THREAD

**Issue by gvilarino** [angstwad/docker.ubuntu#125]
setting the `docker_opts` role parameter, even if it does generate the `/etc/default/docker` file properly, has no effect on the latest Ubuntu/Debian + docker versions because the docker daemon is managed via `systemd`.

As per the official docs, the best and most platform-independent way of configuring the docker daemon is by using [the JSON config file](https://docs.docker.com/engine/reference/commandline/dockerd/#/daemon-configuration-file). For instance:

```json
{
  "dns": ["8.8.8.8", "8.8.4.4"],
  "graph": "/path/to/docker/data"
}
```

If the idea behind this role is to integrate as much as possible with the underlying systems in each distro, then for installations that use `systemd` the better approach would be to [generate the appropriate drop-in files](https://docs.docker.com/engine/admin/systemd/#/custom-docker-daemon-options) and reload the daemon info via `systemctl`:

```
$ systemctl daemon-reload

$ systemctl restart docker
```

**Comment by angstwad** [comment]
I'm happy to take a PR that implements these changes, provided it does not affect older versions of Debian and Ubuntu.  If it does, we'll have to come up with a split solution for old and new.

**Comment by gvilarino** [comment]
@angstwad from the docs and what I've tried out, the `/etc/docker/daemon.json` is sort of the "works everywhere" solution, although there might be gotchas with `systemd` or older ubuntu versions (12)

Happy to help in any way possible with this one.

**Comment by angstwad** [comment]
That's fine.  If you want to implement this, provide a PR.  I doubt I'll get around to it, but I'll be responsive to reviewing and merging it in.

**Comment by gvilarino** [comment]
Good. Any tips on where to start?

**Comment by angstwad** [comment]
Yeah, I think the bulk of the changes that need to happen are in here: https://github.com/angstwad/docker.ubuntu/blob/master/tasks/main.yml#L83-L124

We just have to make sure that we set the options in the right places and account for the different init systems, and modify the right job/service files to force Docker to  use a config file (if necessary)

**Comment by gvilarino** [comment]
So, I've been taking a look and found that the code is actually wel thought, and that part you highlighted *should* make stuff work under `systemd`, but for some reason it still doesn't consider the system to be a `systemd` enabled distro.

[These lines](https://github.com/angstwad/docker.ubuntu/blob/master/tasks/main.yml#L78-L81) are supposed to check it (and they do, I've debugged it on the same host), but it seems either the rest of the tasks are ignoring the result, or something else.

I've tried those two fact-settings in a sample playbook and the same host, and they behave as expected, so I can't tell why the fact is not being considered in the later tasks

**Comment by gvilarino** [comment]
Ok, progress: this wasn't working for me because I was running `1.0`. On `2.0`. Really sorry for this; I keep forgetting to update my galaxy roles in ansible tower.

Closing.
