### ISSUE TITLE
Proxy setting for Ubuntu 16.04

### ISSUE THREAD

**Issue by mtbvang** [angstwad/docker.ubuntu#132]
Ubuntu 16.04 uses systemd and the current proxy configurations did not work for me. I was able to test the install using the hello-world test after applying the systemd specific proxy configurations mentioned in:

http://stackoverflow.com/questions/26550360/docker-ubuntu-behind-proxy

I'm going to work on the fix and submit a pull request.

**Comment by angstwad** [comment]
@mtbvang Yes and also the tests in travis.  I'm eyeballing a lot of PRs ATM and I'd like more concrete tests in place to prevent mistakes on my part.

**Comment by mtbvang** [comment]
I've done the changes but am still trying to get the tests to run. @angstwad Should I just hold on to the changes until we sort the tests out?

**Comment by angstwad** [comment]
You can open a "work in progress" PR if you want that I can look at

**Comment by lhoss** [comment]
Hi @mtbvang, I saw your PR, glad to see my latest proxy feature fixed for ubuntu 16.04 (I tested only in 14.04)
Let me allow some PR comments & suggestions

**Comment by lhoss** [comment]
@mtbvang updates?
else I might take over the PR resp. fork from it

**Comment by lhoss** [comment]
there's an open PR fixing this issue: https://github.com/angstwad/docker.ubuntu/pull/160
that just needs some more work

**Comment by brandonkal** [comment]
It looks like this issue should be closed as it is merged...
