### ISSUE TITLE
Fails on Ubuntu 16.04 with latest Ansible installed

### ISSUE THREAD

**Issue by dswersky** [angstwad/docker.ubuntu#138]
Playbook exits with one "OK" (localhost) and runs no tasks under Ansible 2.2.1.0 on Ubuntu 16.04 Desktop.  Downgrading to 2.0.0.2 fixes the issue.

**Comment by tngan** [comment]
I am using Ansible 2.2.1.0, and the following errors are logged.

```
TASK [angstwad.docker_ubuntu : Install linux-image-extra-* packages to enable AuFS driver] ***
failed: [corvid-dev] (item=[u'linux-image-extra-4.8.6-x86_64-linode78', u'linux-image-extra-virtual']) => {"failed": true, "item": ["linux-image-extra-4.8.6-x86_64-linode78", "linux-image-extra-virtual"], "msg": "No package matching 'linux-image-extra-4.8.6-x86_64-linode78' is available"}
```

**Comment by angstwad** [comment]
@dswersky I'm not sure, but I wonder if it has to do with role metadata checks?  At any rate, I added `xenial` to the role metadata

@tngan I think that has something to do with Linode's `uname -r` output is causing the install [here](https://github.com/angstwad/docker.ubuntu/blob/master/tasks/main.yml#L33-L42) to fail.  Open to suggestions on how to address that.

**Comment by angstwad** [comment]
Can't reproduce on 2.2.1.0
