### ISSUE TITLE
ERROR! 'check_mode' is not a valid attribute for a Task

### ISSUE THREAD

**Issue by fuzzyami** [angstwad/docker.ubuntu#149]
Hye there. 
I suspect that a recent update broke backward comparability with Ansible versions < 2.2.
we're getting the following

'ERROR! 'check_mode' is not a valid attribute for a Task'

when running with ansible 2.0
(which makes sense, since according to the docs, this is only supported since 2.2):
http://docs.ansible.com/ansible/playbooks_checkmode.html

@liorama

**Comment by liorama** [comment]
It fails on the `check_mode` attribute of the `Read uname` shell task on line 27.
Note that the project's Ansible Galaxy page says it's minimum Ansible version is 1.2.

**Comment by jonathangreen** [comment]
I'm also seeing this one.

**Comment by surudoiryu** [comment]
Same here.

**Comment by angstwad** [comment]
This is resolved in #152, I reverted a merge of this option. My fault for not thinking it through fully.

**Comment by liorama** [comment]
We will never ever forgive you....just kiddin`, cool thanks.
