### ISSUE TITLE
docker-ce-17.06 suggestion for new default variables

### ISSUE THREAD

**Issue by DBLaci** [angstwad/docker.ubuntu#171]
docker-engine and old apt sources / keys are deprecated, see:

https://github.com/moby/moby/issues/31514

I added these to my group varialbes:

```
apt_key_url: https://download.docker.com/linux/ubuntu/gpg
apt_key_sig: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
apt_repository: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} test"
docker_pkg_name: "docker-ce"
```
These values are from: https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-using-the-repository

This way I can install (the role upgrades/changes) to docker-ce-17.06

I suggest changing the default/vars.yml values to these.

**Comment by angstwad** [comment]
Can you submit a PR for this?

**Comment by thejmazz** [comment]
I also had to change `docker.conf` from

```
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon -H fd:// $DOCKER_OPTS
```

to

```
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -H fd:// $DOCKER_OPTS
```

Else systemd would keep restarting until it decided to fail

**Comment by angstwad** [comment]
44ba18f implements docker-ce stuff.
