### ISSUE TITLE
Ubuntu 16.04 error: 'ansible_lsb' is undefined

### ISSUE THREAD

**Issue by sylnsr** [angstwad/docker.ubuntu#172]
- New Ubuntu 16.04 EC2 instance with all packages updated
- Ansible 2.3

```
fatal: [org-mas.dev-odoo._______________.com]: FAILED! => {"failed": true, "msg": 
"The conditional check 'ansible_lsb.id|lower == \"ubuntu\" and ( ansible_distribution_version|version_compare('12.04', '<') or ansible_distribution_version|version_compare('12.10', '=') )' failed. 
The error was: error while evaluating conditional (ansible_lsb.id|lower == \"ubuntu\" 
and ( ansible_distribution_version|version_compare('12.04', '<') or ansible_distribution_version|version_compare('12.10', '=') )): 'ansible_lsb' is undefined
The error appears to have been in '/etc/ansible/roles/angstwad.docker_ubuntu/tasks/main.yml': 
line 6, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:

- name: Fail if not a new release of Ubuntu
  ^ here
"}
```

**Comment by angstwad** [comment]
I cannot replicate this on a 16.04 EC2 instance fully updated running Ansible 2.3.1.0.

**Comment by t4ec** [comment]
Just in case. I had the same problem. It turned out that EC2 Ubuntu 16.04 does not have pre-installed Python, so I had to set

`gather_facts: False`

and install Python with `raw` command

and because of `gather_facts: False` ansible_lsb variable was undefined. Removing described flag from playbook had solved the issue.

**Comment by sylnsr** [comment]
@t4ec , I concur this solution. I think my report was misunderstood when I indicated that my target was "updated".  So to be clear, "updated" simply means _existing packages from a fresh install are updated._ Updated does not mean extra packages are installed from a non-standard (default) install". That seems to have been assumed.
