### ISSUE TITLE
Docker process failing at task 'Clean previous docker-py package if installing docker.' due to version_compare issue

### ISSUE THREAD

**Issue by cammanderson** [angstwad/docker.ubuntu#173]
Hi Guys, 

Encountering the following issue:

FAILED! => {"failed": true, "msg": "The conditional check '(_pip_install_docker or pip_install_docker_compose) and _pip_docker_package_name == 'docker'' failed. The error was: {{ 'docker-py' if _pip_version_docker | version_compare('1.10.6', '<=') else 'docker' }}: Version comparison: unorderable types: str() < int()\n\nThe error appears to have been in '/etc/ansible/roles/angstwad.docker_ubuntu/tasks/main.yml': line 179, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# See vars/main.yml for more information on this.\n- name: Clean previous docker-py package if installing docker.\n  ^ here\n"}

I have tried running 2.4.2 and 2.5.0 and still encounter the issue. I have also tried ansible 2.0.0.2 as well as 2.3.1.0.

ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

Is there something that I am doing wrong? Any help in diagnosing would be ace.

Thanks
Cameron

**Comment by angstwad** [comment]
Can you see if #170 fixes your issue?  I haven't been able to replicate that issue but if it fixes it, give me a thumbs up in #170 and I'll merge it in.

**Comment by cammanderson** [comment]
Thanks for the help, it definitely looks like the same issue. I'm not sure how to target that specific PR in docker to test.. :-(

**Comment by cammanderson** [comment]
Actually, scratch that, I will check it out sorry!

**Comment by cammanderson** [comment]
Fix #170 appeared to work for me, the issue is resolved.
