### ISSUE TITLE
Debian ansible_distribution_version can't be compared to '8.5' with latest ansible

### ISSUE THREAD

**Issue by fredleger** [angstwad/docker.ubuntu#184]
Hi,

Running on a Debian 8.9 it seems that the test done on the ansible_distribution_version can't be succesfull event if the criteria is met (8.9 > 8.5).

On my box a "ansible -m setup box" give me the following version:
"ansible_distribution_version": "8"

**Comment by fredleger** [comment]
2 ways :
- check only if >= 8
- check the ansible_lsb.description 
```JSON
"ansible_lsb": {
            "codename": "jessie",
            "description": "Debian GNU/Linux 8.9 (jessie)",
            "id": "Debian",
            "major_release": "8",
            "release": "8"
        },
```

**Comment by angstwad** [comment]
I'll take a PR that resolves the failing version comparison.
