### ISSUE TITLE
GNUPG-curl not matching package for Debian 9

### ISSUE THREAD

**Issue by dvdred** [angstwad/docker.ubuntu#188]
I'm trying to use this role but i get this error. The host is Debian 9 with a fresh installation.
```
TASK [angstwad.docker_ubuntu : Ensure GNUPG-curl is available for https] *********************************************************************************************************************
fatal: [test.local]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'gnupg-curl' is available"}
```

**Comment by angstwad** [comment]
This should have been resolved in https://github.com/angstwad/docker.ubuntu/tree/v3.2.0.  Can you update, try again, and reopen if you encounter issues?

**Comment by dvdred** [comment]
I have updated. It works well now, thank you! But I have another little issue (I will not open a new issue on this project but i want to notice it to you): if I run ansible using the root user, all runs smoothly, but if I use a sudoer user, the role blocks during the "Add Docker repository" phase.
`
TASK [angstwad.docker_ubuntu : Add Docker repository and update apt cache] *******************************************************************************************************************
fatal: [test.local]: FAILED! => {"changed": false, "failed": true, "msg": "[Errno 13] Permission denied: '/etc/apt/.sources.list-qNEwh9'"}
`
