### ISSUE TITLE
Broken proxy.conf file is created with incorrect proxy values on v3.3.0

### ISSUE THREAD

**Issue by crazysaem** [angstwad/docker.ubuntu#189]
Running this ansible role with everything left on default will now create this proxy.conf file on `v3.3.0`:
`/etc/systemd/system/docker.service.d/proxy.conf`:
```
[Service]
Environment="HTTP_PROXY= HTTPS_PROXY= NO_PROXY="
```

Thus e.g. `docker pull hello-world` will fail with the following:
```
Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp :0: getsockopt: connection refused
```

Workaround: Setting the following vars to an empty string solves the issue, and does not create the broken proxy.conf file anymore:
(The `proxy.conf` file also needs to be deleted manually)
```
vars:
  docker_http_proxy: ''
  docker_https_proxy: ''
```

Since this works fine on `v3.2.0`, the issue must've been introduced here https://github.com/angstwad/docker.ubuntu/pull/160/files

**Comment by dleehr** [comment]
I'm seeing this as well. Thanks for the report and the fix!
