### ISSUE TITLE
set http proxy wrongly for systemd

### ISSUE THREAD

**Issue by lijun-hanson** [angstwad/docker.ubuntu#193]
The current generated proxy.conf for systemd docker is following:
[Service]
Environment="http_proxy=<address> https_proxy=<address> no_proxy="
It doesn't work, and shall be changed to following result:
[Service]
Environment="http_proxy=<address>" "https_proxy=<address>" "no_proxy="
It could be found in docker reference doc: [https://docs.docker.com/engine/admin/systemd/#httphttps-proxy](url)

**Comment by escalate** [comment]
This is fixed with PR #196
