### ISSUE TITLE
include: deprecated

### ISSUE THREAD

**Issue by strarsis** [angstwad/docker.ubuntu#195]
````
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or
'include_tasks' for dynamic inclusions. This feature will be removed in a future release. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The module documentation details
 page may explain more about this rationale.. This feature will be removed in a future release. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.
````

https://github.com/angstwad/docker.ubuntu/blob/5fe2526a300cda6dae0aea4472e7287c12553ca6/tasks/main.yml#L22
https://github.com/angstwad/docker.ubuntu/blob/7f1c0c0c92045fc646d3c7b065ec6213db5c72c5/docker.yml#L9 (albeit commented out)

**Comment by Darkknight33** [comment]
The depreciated feature isn't scheduled to be removed until 2.8. If one uses the replacement commands suggested in the documentation, it breaks compatibility with anything earlier than v2.4. Maybe that's a reason to wait until 2.8 is actually on the horizon. Just a thought.

**Comment by sivel** [comment]
`include` has been un-deprecated: https://github.com/ansible/ansible/pull/35843

**Comment by kachkaev** [comment]
I just upgraded the role and am seeing quite a lot of these warnings:

```
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|version_compare`
use `result is version_compare`. This feature will be removed in version 2.9. Deprecation warnings can
be disabled by setting deprecation_warnings=False in ansible.cfg.
```

`ansible 2.6.2`

**Comment by kachkaev** [comment]
Looks like `include` is deprecated again 😁

```
[DEPRECATION WARNING]: "include" is deprecated, use include_tasks/import_tasks instead. This feature will be
removed in version 2.16. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

My `ansible --version` is `2.12.1`. Relevant PR: https://github.com/ansible/ansible/pull/71262
