### ISSUE TITLE
Deprecation warnings in Ansible 2.7

### ISSUE THREAD

**Issue by kachkaev** [angstwad/docker.ubuntu#221]
I upgraded ansible to [2.7.0b1](https://github.com/ansible/ansible/releases/tag/v2.7.0b1) in order to use new [`docker_swarm`](https://docs.ansible.com/ansible/devel/modules/docker_swarm_module.html) and [`docker_swarm_service`](https://docs.ansible.com/ansible/devel/modules/docker_swarm_service_module.html) modules. Re-running a playbook that involves `angstwad.docker_ubuntu` generated quite a few of these warnings:

```
TASK [angstwad.docker_ubuntu : Install backported trusty kernel onto 12.04] ****
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via
squash_actions is deprecated. Instead of using a loop to supply multiple items
and specifying `pkg: {{ item }}`, please use `pkg: [u'linux-image-generic-lts-
trusty', u'linux-headers-generic-lts-trusty']` and remove the loop. This
feature will be removed in version 2.11. Deprecation warnings can be disabled
by setting deprecation_warnings=False in ansible.cfg.
```

Unfortunately I'm quite inexperienced in python or ubuntu management, so am not sure if I can propose a PR that fixes this. However, I hope that reporting the issue anyway will make everyone's lifes easier once 2.7 stable is released.

How could this problem be approached?

**Comment by angstwad** [comment]
The deprecation indicates we have until Ansible version 2.11.  That's quite some time.

**Comment by arhue** [comment]
@angstwad The #223 PR should fix this. I guess you can close this.
