### ISSUE TITLE
Does this module still follow Docker install best practices?

### ISSUE THREAD

**Issue by angstwad** [angstwad/docker.ubuntu#228]
Does this still follow best practices?  Does it still do what the [official Docker install](https://github.com/docker/docker-install) would do?  Are there better ways to reliably install Docker, like with [Docker Machine](https://github.com/docker/machine)?

**Comment by dirkcuys** [comment]
This still seems to me like a good way to install docker using ansible. I don't know Docker Machine, but seems half way between a tool like [terraform](https://www.terraform.io/) and ansible

**Comment by angstwad** [comment]
Hey, so this has been fun, but I don't actively maintain this module anymore, I don't stay up-to-date on Docker install best practices, and rely entirely on PRs to keep this updated.  It's probably worth stating for the record.  The world has changed so much since I originally created this module, I wouldn't recommend this approach for working with Docker or containers in any production capacity.  I haven't had a use case for it in years.

**Comment by dirkcuys** [comment]
Fun indeed, I've been using this role for about 5 years. Thanks for sharing!

**Comment by angstwad** [comment]
I'm honestly surprised to hear that.  Well, best of luck going forward.  If you find a bug first, and you most certainly will since I never use it, please drop a PR...otherwise, feel free to fork and run with it

**Comment by dsteinkopf** [comment]
I‘ve also been using this for long time now. Thank you!
If anybody does a fork with good improvement without PR back to here, I‘d be glad to hear about it.
