### ISSUE TITLE
Keyserver throws error

### ISSUE THREAD

**Issue by safredAAs** [angstwad/docker.ubuntu#234]
`FAILED! => {"changed": false, "cmd": "/usr/bin/apt-key adv --no-tty --keyserver hkp://ha.pool.sks-keyservers.net --recv @@key@@", "msg": "Error fetching key @@key@@ from keyserver: hkp://ha.pool.sks-keyservers.net", "rc": 2, "stderr": "gpg: requesting key @@key@@ from hkp server ha.pool.sks-keyservers.net\ngpg: keyserver timed out\ngpg: keyserver receive failed: keyserver error\n", "stderr_lines": ["gpg: requesting key @@key@@ from hkp server ha.pool.sks-keyservers.net", "gpg: keyserver timed out", "gpg: keyserver receive failed: keyserver error"], "stdout": "Executing: /tmp/tmp.@@key@@/gpg.1.sh --no-tty\n--keyserver\nhkp://ha.pool.sks-keyservers.net\n--recv\@@key@@\n", "stdout_lines": ["Executing: /tmp/tmp.k5482ux8wo/gpg.1.sh --no-tty", "--keyserver", "hkp://ha.pool.sks-keyservers.net", "--recv", "@@key@@"]}`

When trying to include the role in an ansible script, we get timeout errors from the keyserver. Is this known, and/or how can this be fixed?

Thank you!

**Comment by angstwad** [comment]
Sounds like a network issue.  Validate network connectivity to the keyserver.
