### ISSUE TITLE
Python3 in Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by herangstl** [angstwad/docker.ubuntu#237]
Python 2 has been removed from Ubuntu 20.04 LTS. Imho this change should be reflected in this project here.

Currently one has to set the variable ansible_python_interpreter explicitly to something with "python3".

**Comment by angstwad** [comment]
That's an implementation detail for Ansible that is not meant to be solved by this module.

**Comment by herangstl** [comment]
Python version is already gathered by the setup_module and can be accessed by "ansible_python_version".

E.g. 
```
ansible -m setup localhost | grep ansible_python_version
       "ansible_python_version": "3.6.1",
```

Why not use this?
