### ISSUE TITLE
Apt keyserver is deprecated

### ISSUE THREAD

**Issue by tdelacour** [angstwad/docker.ubuntu#244]
Looks like the keyserver defined here is no longer available: https://github.com/angstwad/docker.ubuntu/blob/master/defaults/main.yml#L29

**Comment by aircraft-cerier** [comment]
if you set this in your playbook vars it will use dockers official key:
`apt_key_url: https://download.docker.com/linux/ubuntu/gpg`

**Comment by tdelacour** [comment]
@aircraft-cerier cool, thanks! That's essentially the workaround we used and can confirm it resolves the problem :)
