### ISSUE TITLE
/etc/default/docker does not exists on Ubuntu 14.04

### ISSUE THREAD

**Issue by sirex** [angstwad/docker.ubuntu#29]
See this comment: https://github.com/angstwad/docker.ubuntu/commit/e1380bf1639259e1d33d4800bd26a25d2b8dbd16#commitcomment-9975113

Related issue: #23

**Comment by angstwad** [comment]
Is this only for the docker.io package?  I'm curious if the upstream docker repo differs from the Canonical package.

**Comment by sirex** [comment]
Not sure, how to check that without installing lxc-docker.

Here is what I tried:
    
    $ wget http://get.docker.io/ubuntu/pool/main/l/lxc-docker/lxc-docker_1.5.0_i386.deb   
    --2015-03-01 23:55:17--  http://get.docker.io/ubuntu/pool/main/l/lxc-docker/lxc-docker_1.5.0_i386.deb
    Ieškoma get.docker.io (get.docker.io)... 162.242.195.84
    Jungiamasi prie get.docker.io (get.docker.io)|162.242.195.84|:80... prisijungta.
    HTTP užklausa išsiųsta, laukiama atsakymo... 403 Forbidden
    2015-03-01 23:55:18 KLAIDA 403: Forbidden.


    $ wget http://get.docker.io/ubuntu/pool/main/l/lxc-docker/lxc-docker_1.5.0_amd64.deb -q
    $ dpkg-deb -c lxc-docker_1.5.0_amd64.deb 
    drwx------ 0/0               0 2015-02-10 20:34 ./
    drwxr-xr-x 0/0               0 2015-02-10 20:34 ./usr/
    drwxr-xr-x 0/0               0 2015-02-10 20:34 ./usr/share/
    drwxr-xr-x 0/0               0 2015-02-10 20:34 ./usr/share/doc/
    drwxr-xr-x 0/0               0 2015-02-10 20:34 ./usr/share/doc/lxc-docker/
    -rw-r--r-- 0/0             140 2015-02-10 20:34 ./usr/share/doc/lxc-docker/changelog.Debian.gz


    $ wget http://lt.archive.ubuntu.com/ubuntu/pool/universe/d/docker.io/docker.io_1.0.1\~dfsg1-0ubuntu1\~ubuntu0.14.04.1_amd64.deb -q
    $ dpkg-deb -c docker.io_1.0.1\~dfsg1-0ubuntu1\~ubuntu0.14.04.1_amd64.deb | grep /etc/default
    drwxr-xr-x root/root         0 2014-08-21 20:09 ./etc/default/
    -rw-r--r-- root/root       493 2014-06-20 02:11 ./etc/default/docker.io

**Comment by DanielCaldwell** [comment]
I'm getting this issue as well. Is there a good way of overriding this file?

**Comment by angstwad** [comment]
I'll call this resolved in #57.  Thanks @DanielCaldwell for the PR.  

Long term, I'd like to do version checking to modify the right file in the right place automagically, but for now, a variable works.
