### ISSUE TITLE
Ubuntu 14.04 should install linux-image-extra-* as per official install script

### ISSUE THREAD

**Issue by MrMMorris** [angstwad/docker.ubuntu#53]
In order to prevent the use of devicemapper which is total crap (https://github.com/docker/docker/issues/8176), we should install `linux-image-extra-$(uname -r)` and `linux-image-extra-virtual` as per https://github.com/docker/docker/blob/b89d04dd62e1a779f449804772c5bc5b64af65e8/hack/install.sh#L126-L145

**Comment by angstwad** [comment]
Agreed.  Got a PR?  :)

**Comment by MrMMorris** [comment]
Maybe just `install_kernel_extras: true`? :smirk: Not sure how best to handle this. I seems like all versions of Ubuntu would now need a reboot? I myself am more inclined to cut my own AMI with those packages already...

I can do a PR if you like when I have a sec. Right now I am trying to fix the fallout of devicemapper sucking the big one

**Comment by angstwad** [comment]
Yeah, I think we'll have to think about it a bit and see how to best
handle this.  We probably want to prevent reboots at all costs, but
install the right packages for sure to prevent devicemapper from being
used.

**Comment by shirkevich** [comment]
I've just installed linux-image-extra-virtual and it helped to use aufs without reboot, tested on ubuntu-14.04.

**Comment by angstwad** [comment]
This has been open awhile so it's definitely time to do something about it.  Setting `install_kernel_extras: yes` when invoking the role as a parameterized role will force the installation of `linux-image-extra-$kernel_version` and as of a883229 will also install `linux-image-extra-virtual.

I think that resolves this issue.
