### ISSUE TITLE
on ubuntu 15.04 service doesn't start on server reboot

### ISSUE THREAD

**Issue by lalop** [angstwad/docker.ubuntu#58]
Hello,
I use this role to provision an ubuntu server, if the server restarts docker doesn't start with it.
Is there a way to setup that in this playbook ?

Thank you

**Comment by angstwad** [comment]
Docker should start, at least it did in my experience.  Perhaps something changed.  I'll take a look at this when I have some time.

**Comment by lalop** [comment]
ok thank you

**Comment by PikachuEXE** [comment]
Any update on this?
I experience the same issue on 14.04
The service is installed but does not start after reboot

**Comment by PikachuEXE** [comment]
I just found [a reference for Ubuntu](https://docs.docker.com/engine/installation/linux/ubuntulinux/#/configure-docker-to-start-on-boot)

**Comment by angstwad** [comment]
That reference is for systems with systemd; you're having issues with sysvinit and upstart.  I think it uses a sysvinit script.  

I'd take a PR using the systemd and service modules enabling the docker service with an optional variable override.

**Comment by angstwad** [comment]
This is almost 3 years old, I'm closing.  If it's a real issue let's reopen.
