### ISSUE TITLE
Getting error while downloading GPG key

### ISSUE THREAD

**Issue by pradeepchhetri** [angstwad/docker.ubuntu#64]
Here is the error which i am getting starting recently:

```
TASK: [docker.ubuntu | Add Docker repository key] *****************************
failed: [test-host] => {"failed": true}
msg: Failed to download key at http://get.docker.com/gpg: Request failed: <urlopen error [Errno 1] _ssl.c:510: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure>
```

**Comment by tehranian** [comment]
I'm getting this for the past few days too.

**Comment by angstwad** [comment]
Can you guys provide some information for me real quick so I can try to replicate?  

1. Version of Ansible
1. -`vvvv` output of a run causing this
1. Target machine ubuntu version
1. Target machine python version

**Comment by tehranian** [comment]
I was hitting this because I was on bafa10bf6ed73a1681761e55bc0dc79b285cb63b.

The change at https://github.com/angstwad/docker.ubuntu/pull/62 fixed this for me.

Thanks!
Dan

**Comment by craigtracey** [comment]
@tehranian ltns! Ran into the same issue with my own playbooks. Thanks for the heads up :+1:

**Comment by tehranian** [comment]
@craigtracey Fancy seeing you here! Glad I could help.

**Comment by fiunchinho** [comment]
Should we close this one?
