### ISSUE TITLE
No release

### ISSUE THREAD

**Issue by kosssi** [angstwad/docker.ubuntu#66]
Hello,

Can you create a release ? and update your role in galaxy to add this release ?

Thanks,

**Comment by angstwad** [comment]
This role won't re-import due to what appears to be a bug in Galaxy.  I've known about it for a while now and contacted Ansible a few times, but I reached back out to them to see what's wrong.

We'll have to wait until I hear from them.

**Comment by kosssi** [comment]
We don't have need galaxy to have release ;) But we need a tag in your repo ;)

In my requirements.yml : 

    - src: https://github.com/angstwad/docker.ubuntu
      version: v1.0.0

If you want see the documentation : http://docs.ansible.com/ansible/galaxy.html

**Comment by angstwad** [comment]
Done.

**Comment by kosssi** [comment]
Thanks, @angstwad if you want to know more for release number you can read this http://semver.org/spec/v2.0.0.html ;)
