### ISSUE TITLE
docker_pkg_name changed?

### ISSUE THREAD

**Issue by EliFinkelshteyn** [angstwad/docker.ubuntu#67]
I've been using this for a while and noticed that docker_pkg_name no longer works the way it used to. The default package is now docker-engine and you can no longer install specific packages with options like: `docker_pkg_name: lxc-docker-1.6.2`. Is there a new workaround here to peg the version? Installing whatever version happens to be the newest feels very dangerous.

**Comment by angstwad** [comment]
http://docs.ansible.com/ansible/apt_module.html

docker_pkg_name is passed directly to apt name, so you can package by overwriting the default value, for example: docker-engine=1.6.2

**Comment by EliFinkelshteyn** [comment]
For anyone seeing this in the future, @angstwad's answer above does not work (for me at least). The Docker versions now have some part of the Ubuntu version name in them, you'll have to make references like `docker-engine=1.8.2-0~trusty`.
