### ISSUE TITLE
Needless "changed" 

### ISSUE THREAD

**Issue by hansbogert** [angstwad/docker.ubuntu#70]
I'm not sure about how the pip module works, but is really necessary that every time a playbook runs the following should happen (the 2 last install are always _changed_):

```
TASK: [angstwad.docker_ubuntu | Upgrade latest pip, setuptools, docker-py and docker-compose with pip] ***
ok: [fe-web1-acc] => (item={'version': u'latest', 'name': 'pip'})
ok: [fe-web1-acc] => (item={'version': u'latest', 'name': 'setuptools'})
changed: [fe-web1-acc] => (item={'version': u'latest', 'name': 'docker-py'})
changed: [fe-web1-acc] => (item={'version': u'latest', 'name': 'docker-compose'})
```

**Comment by angstwad** [comment]
pip module's idempotent operations leave a bit to be desired.  two options:

1. fix in upstream ansible pip module
1. provide a pull request that uses the `changed_when` key to modify this behavior to make the play idempotent
`changed_when` docs are [here](https://docs.ansible.com/ansible/playbooks_error_handling.html#overriding-the-changed-result).

**Comment by hansbogert** [comment]
If it's pip which is to blame, so be it.
Thanks for speedy response.
