### ISSUE TITLE
unable to parse package file

### ISSUE THREAD

**Issue by levinotik** [angstwad/docker.ubuntu#72]
I've been using this role for a while, but suddenly having some trouble with it. I get the following error when running this:

```
TASK: [angstwad.docker_ubuntu | Install (or update) docker package] *********** 
<10.0.1.30> REMOTE_MODULE apt name=docker-engine state=present
failed: [10.0.1.30] => {"failed": true, "parsed": false}
BECOME-SUCCESS-mrlqxwempmkpaykhqkiiphryxqgzmzgx

Traceback (most recent call last):

  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1445550195.85-96942197658441/apt", line 2258, in <module>

    main()

  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1445550195.85-96942197658441/apt", line 554, in main

    cache = apt.Cache()

  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 107, in __init__

    self.open(progress)

  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 151, in open

    self._cache = apt_pkg.Cache(progress)

SystemError: E:Unable to parse package file /var/lib/apt/lists/us-west-2.ec2.archive.ubuntu.com_ubuntu_dists_trusty-updates_main_i18n_Translation-en (1), E:The package lists or status file could not be parsed or opened.

OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014

debug1: Reading configuration data /etc/ssh/ssh_config

debug1: /etc/ssh/ssh_config line 19: Applying options for *

debug1: auto-mux: Trying existing master

debug1: mux_client_request_session: master session id: 2

Shared connection to 10.0.1.30 closed.



FATAL: all hosts have already failed -- aborting
```

Any help would be greatly appreciated, thank you!

**Comment by angstwad** [comment]
That looks like a apt problem to me.  I found [this thread](https://askubuntu.com/questions/561276/my-repos-became-corrupted-unable-to-parse-package-file) on Ask Ubuntu and some have reported it happening with some frequency in AWS. 

If this became a regular occurrence, I'd personally run a playbook that removes the apt cache first, then calls the `docker.ubuntu` role.

If you're booting from a snapshot, I guess I'd try and see if a newer Ubuntu build resolves the issue.  Ubuntu's cloud site has their latest 14.04 builds [here](http://cloud-images.ubuntu.com/trusty/current/).

**Comment by levinotik** [comment]
Yes, looked like a local issue. Found the same thread and that fixed it. I should have looked more closely before opening this issue :) Thanks for the reply.
