### ISSUE TITLE
Option to install specific version of docker

### ISSUE THREAD

**Issue by martinmicunda** [angstwad/docker.ubuntu#73]
Is there option to install specific version of docker e.g. using env variable?

**Comment by angstwad** [comment]
Not at this time. What are you trying to achieve that necessitates
environment variables?

On Monday, October 26, 2015, Martin Micunda <notifications@github.com>
wrote:

> Is there option to install specific version of docker e.g. using env
> variable?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angstwad/docker.ubuntu/issues/73>.
>


-- 
-Paul
Sent from my iPhone

**Comment by martinmicunda** [comment]
I am using another [docker-compose](https://github.com/weareinteractive/ansible-docker-compose) role and there is option to specify version of docker-compose and as docker-compose kind of depends on docker I was thinking it would be nice to specify exactly version of docker.

**Comment by angstwad** [comment]
You can use the parameter `docker_pkg_name` and set it to `docker-machine=1.8.3-0~trusty`, or some other valid version of docker-machine or docker.io as required.

To see the available versions, use `apt-cache showpkg docker-engine` or the right package as required.
